defaults:
  - dataset: hh_rlhf

trainer:
  n_gpus_per_node: 8
  output_dir: outputs/${dataset.name}/train

data:
  train_file: null
  train_eval_save_path: null
  use_all_ref_tokens: 1
  drop_no_variation: 1
  max_length: -1
  shift_reward: 0
  scale_reward: 1

models:
  ref_model_id: Qwen/Qwen2.5-7B-Instruct
  classifier_model_id: Qwen/Qwen2.5-1.5B-Instruct
  classifier_type: Q
  classifier_ckpt_path: null
  init_mode: reuse
  inference_mode: expectation
  loss_type: bce
  use_bias: 0
  dtype: bfloat16

training:
  batch_size: 8
  gradient_accumulation_steps: 1
  num_epochs: 100
  lr: 2e-5
  warmup_steps: -1
  weight_decay: 0.01
  eval_freq: 500
  ckpt_freq: 5000
  eval_max_size: 1000
  seed: 47

wandb:
  enabled: false
  entity: null
  project: PITA
  run_name: ${models.inference_mode}_${dataset.name}
